version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch-node-browsers-legacy
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init 
      - run:
          name: add-buildtools
          command: sudo apt install cmake libmp3lame-dev
      - run:
          name: build
          command: python setup.py bdist_wheel
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  test:
    docker:
      - image: circleci/python:3.6-stretch-node-browsers-legacy
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: pip install `ls *.whl`
      - run: cd tests && python test.py

workflows:
  version: 2
  linux:
    jobs:
      - build
      - test:
          requires:
            - build
